# See https://github.com/bxparks/EpoxyDuino for documentation about using
# EpoxyDuino to compile and run AUnit tests natively on Linux or MacOS.

include ../../.env

APP_NAME := QualitySampleTest
ARDUINO_LIBS := QualitySample AUnit
include $(arduino_ide_dir)/libraries/EpoxyDuino/EpoxyDuino.mk