# See https://github.com/bxparks/EpoxyDuino for documentation about using
# EpoxyDuino to compile and run AUnit tests natively on Linux or MacOS.

include ../../.env

APP_NAME := QualitySampleTest
ARDUINO_LIBS := AUnit QualitySample
ARDUINO_LIB_DIRS := \
	../../src/Sampling
include $(arduino_ide_dir)/libraries/EpoxyDuino/EpoxyDuino.mk