# See https://github.com/bxparks/EpoxyDuino for documentation about using
# EpoxyDuino to compile and run AUnit tests natively on Linux or MacOS.

APP_NAME := QualitySampleTest
ARDUINO_LIBS := QualitySample AUnit
#include ../../../../EpoxyDuino/EpoxyDuino.mk
